server:
  port: 8080
  servlet:
    context-path: /backend
    
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
#    url: jdbc:mysql://host.docker.internal:3306/db_admin_staging?useUnicode=true&characterEncoding=utf8&useSSL=false
#    username: amien
#    password: password
    url: jdbc:mysql://${db-host}:3306/${db-name}?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: ${db-username}
    password: ${db-password}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 20000
      connection-timeout: 30000
      leak-detection-threshold: 30000
      max-lifetime: 180000
      validation-timeout: 3000
      pool-name: HikariPool-1
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    database: PostgreSQL
#    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: MYSQL
    show-sql: false
#    properties:
#      hibernate.jdbc.time_zone: Asia/Jakarta
  mail:
#    host: mail.balia.ae
    host: ${mail-host}
    port: 587
    username: ${mail-username}
    password: ${mail-password}
    protocol: smtp
    test-connection: false
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  messages:
    basename: i18n/messages
    encoding: UTF-8
  servlet: 
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

application:
  jwtSecret: ${jwt-secret}
  jwtExpirationMs: 86400000
  base64Key: ${apps-base64key}
  base64Iv: ${apps-base64iv}
  baseUrl: https://balia.ae
  mail:
    from: admin@balia.ae
    base-url: https://balia.ae
  upload:
    dir: /app/cdn
  cdn:
    url: ${cdn-url}