name: Deploy to VPS
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/balia-be:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/balia-be:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    # Step 5: SSH to VPS and Manage Docker Images
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            # Pull the latest Docker image
            docker pull ${{ secrets.DOCKER_USERNAME }}/balia-be:latest
            
            # Stop and remove the current container (if it exists)
            docker stop balia-be || true
            docker rm balia-be || true
            
            # Remove older images except the latest
            docker images --filter=reference="${{ secrets.DOCKER_USERNAME }}/balia-be" --format "{{.ID}} {{.Tag}}" \
            | grep -v "latest" | awk '{print $1}' | xargs -r docker rmi
            
            # Run the latest container
            docker run -d --name balia-be \
            -p 8181:8080 \
            -e mail-host=${{ secrets.MAIL_HOST }} \
            -e mail-username=${{ secrets.MAIL_USERNAME }} \
            -e mail-password=${{ secrets.MAIL_PASSWORD }} \
            -e jwt-secret=${{ secrets.JWT_SECRET }} \
            -e db-host=${{ secrets.DB_HOST }} \
            -e db-name=${{ secrets.DB_NAME }} \
            -e db-username=${{ secrets.DB_USERNAME }} \
            -e db-password=${{ secrets.DB_PASSWORD }} \
            ${{ secrets.DOCKER_USERNAME }}/balia-be:latest
