name: Deploy to VPS
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build --build-arg NODE_ENV=production -t ${{ secrets.DOCKER_USERNAME }}/next-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/next-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    # Step 5: SSH to VPS and Manage Docker Images
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            # Pull the latest Docker image
            docker pull ${{ secrets.DOCKER_USERNAME }}/next-app:latest
            
            # Stop and remove the current container (if it exists)
            docker stop next-app || true
            docker rm next-app || true
            
            # Remove older images except the latest
            docker images --filter=reference="${{ secrets.DOCKER_USERNAME }}/next-app" --format "{{.ID}} {{.Tag}}" \
            | grep -v "latest" | awk '{print $1}' | xargs -r docker rmi
            
            # Run the latest container
            docker run -d --name next-app \
            -p 8081:3000 \
            -e NODE_ENV=production \
            -e NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }} \
            -e SECRET_KEY=${{ secrets.SECRET_KEY }} \
            ${{ secrets.DOCKER_USERNAME }}/next-app:latest
